Login Page - Qusai
TBolton2000/concord pull request #26
Opened 2020-10-15 21:38 UTC by Qusaiamer

The first phase of login page done

2020-10-15 23:12 UTC, TBolton2000 requested changes
Looks pretty good. Get these revisions changed and then just commit and push to the same branch

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                                    onChange={onTextFieldUpdate(setUserName)}>
Relook over the value and onChange fields of the Tabs component, this is not the way.
For our example, you can just set the value to 0 and do not have an onChange function. 
(By setting it to 0 you are saying that the zeroth tab is currently active, which is the Tab with the Login label)

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                            <CardContent>
Do not wrap everything in the card in its own card content tag. You typically want ONE CardContent section per card. This will help the formatting for the page to be more compact and easier for us to manipulate later.

Remove all other <CardContent>'s other than this one, and keep the last </CardContent>

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +
Do not include unnecessary newlines, try to keep everything clean and concise.

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +import { SignUp } from "./Signup";
Remove unnecessary imports

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                            <CardHeader title='Welcome Back!' />
Only one tab per "level" please.

Quick tip for fixing this in VSCode, highlight all of the lines that you want to change the indentation on and then use tab to add one indentation to all of the lines or use shift+tab to remove one indentation on all of the lines

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                                Submit
This button should probably say "Login"

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                                Submit
Also, tab this in one

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                            {/* <CardContent> "Forgot password?" component={Link} to={/components/} </CardContent> */}
Remove unused code

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                            <CardContent><TextField label="User Name" onChange={onTextFieldUpdate(setUserName)}></TextField></CardContent>
<CardContent>
    <TextField label="User Name" onChange={onTextFieldUpdate(setUserName)} />
</CardContent>

 is cleaner and concise

2020-10-15 23:12 UTC, TBolton2000 commented on src/client/components/Login.tsx
> +                            <CardContent><TextField label="Password" onChange={onTextFieldUpdate(setPassword)}></TextField></CardContent>
Same as above

2020-10-16 03:17 UTC, Qusaiamer reviewed
Thanks, Trevor for the detailed feedback. I fixed the highlighted issues.

2020-10-16 04:18 UTC, TBolton2000 approved these changes
Looks great! Much better!

2020-10-16 04:19 UTC, merged